export default [
  {
    id: 1,
    name: " Koenigsegg",
    image: "/Koenigsegg.png",
    seat_capacity: 7,
    fuel_capacity: 22,
    transmission: "Automatic",
    type: "Sport",
    rental_price_per_day: 413.14,
    color: "#2c05c1",
    availability: true,
  },
  {
    id: 2,
    name: "Nissan Titan GT-R ",
    image: "/NissanGT-R.png",
    seat_capacity: 6,
    fuel_capacity: 42,
    transmission: "Automatic",
    type: "Sport",
    rental_price_per_day: 411.64,
    color: "#0284e3",
    availability: true,
  },
  {
    name: "Rolls -Royce ",
    id: 3,
    image: "/Rolls-Royce.png",
    seat_capacity: 4,
    fuel_capacity: 36,
    transmission: "Manual",
    type: "SUV",
    rental_price_per_day: 78.84,
    color: "#d51e34",
    availability: true,
  },
  {
    id: 4,
    name: "MG ZX Excite",
    image: "/MG-ZX-Exclusice.png",
    seat_capacity: 3,
    fuel_capacity: 19,
    transmission: "Automatic",
    type: "Suv",
    rental_price_per_day: 478.02,
    color: "#87dd09",
    availability: true,
  },
  {
    id: 5,
    name: "All New Rush",
    image: "/AllNewRush.png",
    seat_capacity: 3,
    fuel_capacity: 78,
    transmission: "Automatic",
    type: "Sedan",
    company_name: "National",
    rental_price_per_day: 219.67,
    color: "#0de624",
    availability: true,
  },
  {
    id: 6,
    name: "CR-V",
    image: "/cr-v.png",
    seat_capacity: 4,
    fuel_capacity: 47,
    transmission: "Automatic",
    type: "SUV",
    rental_price_per_day: 102.67,
    color: "#b4ef7d",
    availability: true,
  },
  {
    id: 7,
    name: "All New Terios",
    image: "/AllNewTerios.png",
    seat_capacity: 2,
    fuel_capacity: 56,
    transmission: "Automatic",
    type: "SUV",
    company_name: "Toyota",
    rental_price_per_day: 458.05,
    color: "#54244a",
    availability: true,
  },
  {
    id: 8,
    name: "CR - V Black",
    image: "/CR - V-Black.png",
    seat_capacity: 3,
    fuel_capacity: 29,
    transmission: "Automatic",
    type: "SUV",
    company_name: "Honda",
    rental_price_per_day: 247.24,
    color: "#31e463",
    availability: true,
  },
  {
    id: 9,
    name: "MG ZX Exclusice Skyblue",
    image: "/MG-ZX-Excite-Sky.png",
    seat_capacity: 4,
    fuel_capacity: 88,
    transmission: "Automatic",
    type: "Coupe",
    company_name: "Enterprise",
    rental_price_per_day: 284.97,
    color: "#91b71c",
    availability: true,
  },
  {
    id: 10,
    name: "New MG Zs",
    image: "/NewMG-ZS.png",
    seat_capacity: 6,
    fuel_capacity: 91,
    transmission: "Automatic",
    type: "SUV",
    rental_price_per_day: 467.42,
    color: "#e47031",
    availability: true,
  },
  {
    id: 11,
    name: "All New Terios ",
    image: "/AllNewTerios.png",
    seat_capacity: 1,
    fuel_capacity: 66,
    transmission: "Manual",
    type: "Suv",
    rental_price_per_day: 236.04,
    color: "#fbb6aa",
    availability: true,
  },
  
  {
    id: 12,
    name: "MG ZX Excite",
    image: "/MG-ZX-Excite-Sky.png",
    seat_capacity: 2,
    fuel_capacity: 83,
    transmission: "Automatic",
    type: "Sedan",
    rental_price_per_day: 398.39,
    color: "#96fc71",
    availability: true,
  },
  // {
  //   id: 13,
  //   name: "Toyota Tundra",
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 38,
  //   transmission: "Automatic",
  //   type: "Truck",
  //   company_name: "Enterprise",
  //   rental_price_per_day: 345.98,
  //   color: "#433d0e",
  //   availability: true,
  // },
  // {
  //   name: "GMC Sierra",
  //   id: 14,
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 92,
  //   transmission: "Automatic",
  //   type: "Sedan",
  //   company_name: "Budget",
  //   rental_price_per_day: 475.65,
  //   color: "#724d0a",
  //   availability: true,
  // },
  // {
  //   name: "Porsche Cayenne",
  //   id: 15,
  //   image: null,
  //   seat_capacity: 4,
  //   fuel_capacity: 79,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "National",
  //   rental_price_per_day: 183.12,
  //   color: "#e49724",
  //   availability: true,
  // },
  // {
  //   name: "Buick Enclave",
  //   id: 16,
  //   image: null,
  //   seat_capacity: 8,
  //   fuel_capacity: 46,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "Alamo",
  //   rental_price_per_day: 439.43,
  //   color: "#93c72d",
  //   availability: true,
  // },
  // {
  //   name: "Mercury Mountaineer",
  //   id: 17,
  //   image: null,
  //   seat_capacity: 2,
  //   fuel_capacity: 30,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "Thrifty",
  //   rental_price_per_day: 395.71,
  //   color: "#48809c",
  //   availability: true,
  // },
  // {
  //   name: "Ford Expedition",
  //   id: 18,
  //   image: null,
  //   seat_capacity: 8,
  //   fuel_capacity: 78,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "Sixt",
  //   rental_price_per_day: 205.42,
  //   color: "#78dff2",
  //   availability: true,
  // },
  // {
  //   name: "Nissan Titan",
  //   id: 19,
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 45,
  //   transmission: "Manual",
  //   type: "Truck",
  //   company_name: "Dollar",
  //   rental_price_per_day: 183.79,
  //   color: "#185ec2",
  //   availability: true,
  // },
  // {
  //   name: "Saturn Outlook",
  //   id: 20,
  //   image: null,
  //   seat_capacity: 8,
  //   fuel_capacity: 36,
  //   transmission: "Manual",
  //   type: "Truck",
  //   company_name: "Enterprise",
  //   rental_price_per_day: 258.61,
  //   color: "#d4d90c",
  //   availability: true,
  // },
  // {
  //   name: "Ferrari 488 GTB",
  //   id: 21,
  //   image: null,
  //   seat_capacity: 3,
  //   fuel_capacity: 41,
  //   transmission: "Automatic",
  //   type: "Van",
  //   company_name: "Ferrari Rentals",
  //   rental_price_per_day: 433.54,
  //   color: "#294fb9",
  //   availability: true,
  // },
  // {
  //   name: "Saab 9-3",
  //   id: 22,
  //   image: null,
  //   seat_capacity: 2,
  //   fuel_capacity: 94,
  //   transmission: "Automatic",
  //   type: "Truck",
  //   company_name: "Saab Motors",
  //   rental_price_per_day: 341.92,
  //   color: "#64ef81",
  //   availability: true,
  // },
  // {
  //   name: "Ford Expedition",
  //   id: 23,
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 36,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "Ford Rentals",
  //   rental_price_per_day: 83.16,
  //   color: "#232ff0",
  //   availability: true,
  // },
  // {
  //   name: "Pontiac Grand Prix",
  //   id: 24,
  //   image: null,
  //   seat_capacity: 2,
  //   fuel_capacity: 39,
  //   transmission: "Manual",
  //   type: "Van",
  //   company_name: "Pontiac Rentals",
  //   rental_price_per_day: 493.51,
  //   color: "#70ebcb",
  //   availability: true,
  // },
  // {
  //   name: "Volvo XC90",
  //   id: 25,
  //   image: null,
  //   seat_capacity: 1,
  //   fuel_capacity: 90,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "Volvo Rentals",
  //   rental_price_per_day: 353.71,
  //   color: "#6af994",
  //   availability: true,
  // },
  // {
  //   name: "Ford Explorer",
  //   id: 26,
  //   image: null,
  //   seat_capacity: 6,
  //   fuel_capacity: 89,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "Ford Rentals",
  //   rental_price_per_day: 203.33,
  //   color: "#83d93f",
  //   availability: true,
  // },
  // {
  //   name: "Ford Mustang",
  //   id: 27,
  //   image: null,
  //   seat_capacity: 1,
  //   fuel_capacity: 30,
  //   transmission: "Manual",
  //   type: "Sedan",
  //   company_name: "Ford Rentals",
  //   rental_price_per_day: 485.92,
  //   color: "#df370c",
  //   availability: true,
  // },
  // {
  //   name: "Rolls-Royce Phantom",
  //   id: 28,
  //   image: null,
  //   seat_capacity: 5,
  //   fuel_capacity: 15,
  //   transmission: "Automatic",
  //   type: "Truck",
  //   company_name: "Rolls-Royce Rentals",
  //   rental_price_per_day: 206.78,
  //   color: "#1e9dfd",
  //   availability: true,
  // },
  // {
  //   name: "Saab 9-5",
  //   id: 29,
  //   image: null,
  //   seat_capacity: 4,
  //   fuel_capacity: 21,
  //   transmission: "Manual",
  //   type: "Van",
  //   company_name: "Saab Rentals",
  //   rental_price_per_day: 408.97,
  //   color: "#5de044",
  //   availability: true,
  // },
  // {
  //   name: "Audi Q5",
  //   id: 30,
  //   image: null,
  //   seat_capacity: 6,
  //   fuel_capacity: 21,
  //   transmission: "Manual",
  //   type: "SUV",
  //   company_name: "Audi Rentals",
  //   rental_price_per_day: 162.99,
  //   color: "#fc1211",
  //   availability: true,
  // },
  // {
  //   name: "Chevrolet Malibu",
  //   id: 31,
  //   image: null,
  //   seat_capacity: 2,
  //   fuel_capacity: 22,
  //   transmission: "Automatic",
  //   type: "Sedan",
  //   company_name: "Chevrolet Rentals",
  //   rental_price_per_day: 57.98,
  //   color: "#bdf380",
  //   availability: true,
  // },
  // {
  //   name: "Suzuki Swift",
  //   id: 32,
  //   image: null,
  //   seat_capacity: 6,
  //   fuel_capacity: 92,
  //   transmission: "Manual",
  //   type: "Sedan",
  //   company_name: "Suzuki Rentals",
  //   rental_price_per_day: 476.43,
  //   color: "#0f7815",
  //   availability: true,
  // },
  // {
  //   name: "GMC Sierra",
  //   id: 33,
  //   image: null,
  //   seat_capacity: 2,
  //   fuel_capacity: 81,
  //   transmission: "Automatic",
  //   type: "Sedan",
  //   company_name: "GMC Rentals",
  //   rental_price_per_day: 368.24,
  //   color: "#7b7ef5",
  //   availability: true,
  // },
  // {
  //   name: "Mazda CX-9",
  //   id: 34,
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 17,
  //   transmission: "Manual",
  //   type: "Sedan",
  //   company_name: "Mazda Rentals",
  //   rental_price_per_day: 63.66,
  //   color: "#0b8606",
  //   availability: true,
  // },
  // {
  //   name: "Cadillac Escalade",
  //   id: 35,
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 61,
  //   transmission: "Automatic",
  //   type: "Truck",
  //   company_name: "Cadillac Rentals",
  //   rental_price_per_day: 145.23,
  //   color: "#67fb89",
  //   availability: true,
  // },
  // {
  //   name: "Jaguar F-Pace",
  //   id: 36,
  //   image: null,
  //   seat_capacity: 6,
  //   fuel_capacity: 24,
  //   transmission: "Manual",
  //   type: "SUV",
  //   company_name: "Jaguar Rentals",
  //   rental_price_per_day: 441.76,
  //   color: "#e8174f",
  //   availability: true,
  // },
  // {
  //   name: "Ford Bronco",
  //   id: 37,
  //   image: null,
  //   seat_capacity: 1,
  //   fuel_capacity: 49,
  //   transmission: "Manual",
  //   type: "SUV",
  //   company_name: "Ford Rentals",
  //   rental_price_per_day: 406.47,
  //   color: "#922e9a",
  //   availability: true,
  // },
  // {
  //   name: "BMW X7",
  //   id: 38,
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 93,
  //   transmission: "Automatic",
  //   type: "Truck",
  //   company_name: "BMW Rentals",
  //   rental_price_per_day: 326.4,
  //   color: "#d35a98",
  //   availability: true,
  // },
  // {
  //   name: "Chevrolet Tahoe",
  //   id: 39,
  //   image: null,
  //   seat_capacity: 8,
  //   fuel_capacity: 23,
  //   transmission: "Manual",
  //   type: "Van",
  //   company_name: "Chevrolet Rentals",
  //   rental_price_per_day: 404.3,
  //   color: "#9004e4",
  //   availability: true,
  // },
  // {
  //   name: "Chrysler Ram 1500",
  //   id: 40,
  //   image: null,
  //   seat_capacity: 2,
  //   fuel_capacity: 16,
  //   transmission: "Automatic",
  //   type: "Truck",
  //   company_name: "Chrysler Rentals",
  //   rental_price_per_day: 424.59,
  //   color: "#33e352",
  //   availability: true,
  // },
  // {
  //   name: "Kia Sorento",
  //   id: 41,
  //   image: null,
  //   seat_capacity: 7,
  //   fuel_capacity: 49,
  //   transmission: "Manual",
  //   type: "Truck",
  //   company_name: "Kia Rentals",
  //   rental_price_per_day: 235.08,
  //   color: "#86ddf9",
  //   availability: true,
  // },
  // {
  //   name: "Mercury Mountaineer",
  //   id: 42,
  //   image: null,
  //   seat_capacity: 5,
  //   fuel_capacity: 96,
  //   transmission: "Automatic",
  //   type: "Truck",
  //   company_name: "Mercury Rentals",
  //   rental_price_per_day: 473.81,
  //   color: "#83594e",
  //   availability: true,
  // },
  // {
  //   name: "Oldsmobile Silhouette",
  //   id: 43,
  //   image: null,
  //   seat_capacity: 5,
  //   fuel_capacity: 61,
  //   transmission: "Automatic",
  //   type: "Van",
  //   company_name: "Oldsmobile Rentals",
  //   rental_price_per_day: 322.39,
  //   color: "#a26751",
  //   availability: true,
  // },
  // {
  //   name: "Mitsubishi Outlander",
  //   id: 44,
  //   image: null,
  //   seat_capacity: 4,
  //   fuel_capacity: 67,
  //   transmission: "Manual",
  //   type: "Sedan",
  //   company_name: "Mitsubishi Rentals",
  //   rental_price_per_day: 450.33,
  //   color: "#b8985d",
  //   availability: true,
  // },
  // {
  //   name: "Ford Explorer",
  //   id: 45,
  //   image: null,
  //   seat_capacity: 3,
  //   fuel_capacity: 55,
  //   transmission: "Manual",
  //   type: "SUV",
  //   company_name: "Ford Rentals",
  //   rental_price_per_day: 442.82,
  //   color: "#b4a08c",
  //   availability: true,
  // },
  // {
  //   name: "Acura MDX",
  //   id: 46,
  //   image: null,
  //   seat_capacity: 1,
  //   fuel_capacity: 65,
  //   transmission: "Automatic",
  //   type: "SUV",
  //   company_name: "Acura Rentals",
  //   rental_price_per_day: 122.85,
  //   color: "#de5f13",
  //   availability: true,
  // },
  // {
  //   name: "Dodge Durango",
  //   id: 47,
  //   image: null,
  //   seat_capacity: 5,
  //   fuel_capacity: 69,
  //   transmission: "Automatic",
  //   type: "Sedan",
  //   company_name: "Dodge Rentals",
  //   rental_price_per_day: 206.95,
  //   color: "#404640",
  //   availability: true,
  // },
  // {
  //   name: "Saab 9-3",
  //   id: 48,
  //   image: null,
  //   seat_capacity: 3,
  //   fuel_capacity: 51,
  //   transmission: "Manual",
  //   type: "SUV",
  //   company_name: "Saab Rentals",
  //   rental_price_per_day: 257.66,
  //   color: "#04e504",
  //   availability: true,
  // },
  // {
  //   name: "Honda Accord",
  //   id: 49,
  //   image: null,
  //   seat_capacity: 8,
  //   fuel_capacity: 25,
  //   transmission: "Automatic",
  //   type: "Sedan",
  //   company_name: "Honda Rentals",
  //   rental_price_per_day: 456.52,
  //   color: "#8a2c83",
  //   availability: true,
  // },
  // {
  //   name: "Mercury Sable",
  //   id: 50,
  //   image: null,
  //   seat_capacity: 4,
  //   fuel_capacity: 10,
  //   transmission: "Automatic",
  //   type: "Sedan",
  //   company_name: "Mercury Rentals",
  //   rental_price_per_day: 376.61,
  //   color: "#c713ca",
  //   availability: true,
  // },
];
