export default [
  {
    id: 1,
    name: "Koenigsegg",
    image: "/Koenigsegg.png",
    gallery: [
      "/Koenigsegg1.jpg",
      "/Koenigsegg2.jpg",
      "/Koenigsegg3.jpg",
      "/Koenigsegg4.jpg",
    ],
    seat_capacity: 7,
    fuel_capacity: 22,
    transmission: "Automatic",
    type: "Sport",
    rental_price_per_day: 413.14,
    previous_rental_price: 450.0,
    color: "#2c05c1",
    availability: true,
    description:
      "Koenigsegg cars represent the pinnacle of hypercar performance, blending innovation, aerodynamics, and extreme power for an unparalleled driving experience.",
  },
  {
    id: 2,
    name: "Nissan Titan GT-R",
    image: "/NissanGT-R.png",
    gallery: [
      "/Nissan Titan GT-R1.jpg",
      "/Nissan Titan GT-R2.jpg",
      "/Nissan Titan GT-R3.jpg",
      "/Nissan Titan GT-R4.jpg",
    ],
    seat_capacity: 6,
    fuel_capacity: 42,
    transmission: "Automatic",
    type: "Sport",
    rental_price_per_day: 411.64,
    previous_rental_price: 430.5,
    color: "#0284e3",
    availability: true,
    description:
      "Inspired by the race track, the Nissan Titan GT-R delivers breathtaking speed, precision handling, and a dynamic design that embodies pure performance.",
  },
  {
    id: 3,
    name: "Rolls-Royce",
    image: "/Rolls-Royce.png",
    gallery: [
      "/Rolls-Royce1.jpg",
      "/Rolls-Royce2.jpg",
      "/Rolls-Royce3.jpg",
      "/Rolls-Royce4.jpg",
    ],
    seat_capacity: 4,
    fuel_capacity: 36,
    transmission: "Manual",
    type: "SUV",
    rental_price_per_day: 78.84,
    previous_rental_price: 90.0,
    color: "#d51e34",
    availability: true,
    description:
      "Rolls-Royce is synonymous with luxury and prestige, offering a refined driving experience with exquisite craftsmanship and advanced technology.",
  },
  {
    id: 4,
    name: "MG ZX Excite",
    image: "/MG-ZX-Exclusice.png",
    gallery: [
      "/MG ZX Excite1.jpg",
      "/MG ZX Excite2.jpg",
      "/MG ZX Excite3.jpg",
      "/MG ZX Excite4.jpg",
    ],
    seat_capacity: 3,
    fuel_capacity: 19,
    transmission: "Automatic",
    type: "SUV",
    rental_price_per_day: 478.02,
    previous_rental_price: 500.0,
    color: "#87dd09",
    availability: true,
    description:
      "The MG ZX Excite combines modern styling with practical performance, offering a comfortable ride with impressive fuel efficiency and technology.",
  },
  {
    id: 5,
    name: "All New Rush",
    image: "/AllNewRush.png",
    gallery: [
      "/All New Rush1.jpg",
      "/All New Rush2.jpg",
      "/All New Rush3.jpg",
      "/All New Rush4.jpg",
    ],
    seat_capacity: 3,
    fuel_capacity: 78,
    transmission: "Automatic",
    type: "Sedan",
    company_name: "National",
    rental_price_per_day: 219.67,
    previous_rental_price: 240.0,
    color: "#0de624",
    availability: true,
    description:
      "Designed for versatility and comfort, the All New Rush is a stylish and efficient sedan perfect for both city drives and long road trips.",
  },
  {
    id: 6,
    name: "CR-V",
    image: "/cr-v.png",
    gallery: ["/CR-V1.jpg", "/CR-V2.jpg", "/CR-V3.jpg", "/CR-V4.jpg"],
    seat_capacity: 4,
    fuel_capacity: 47,
    transmission: "Automatic",
    type: "SUV",
    rental_price_per_day: 102.67,
    previous_rental_price: 120.0,
    color: "#b4ef7d",
    availability: true,
    description:
      "The Honda CR-V offers a perfect balance of space, performance, and reliability, making it a favorite among families and adventure seekers alike.",
  },
  {
    id: 7,
    name: "All New Terios",
    image: "/AllNewTerios.png",
    gallery: [
      "/All New Terios1.jpg",
      "/All New Terios2.jpg",
      "/All New Terios3.jpg",
      "/All New Terios4.jpg",
    ],
    seat_capacity: 2,
    fuel_capacity: 56,
    transmission: "Automatic",
    type: "SUV",
    company_name: "Toyota",
    rental_price_per_day: 458.05,
    previous_rental_price: 475.0,
    color: "#54244a",
    availability: true,
    description:
      "With its bold design and superior off-road capability, the All New Terios delivers adventure-ready performance for any journey.",
  },
  {
    id: 8,
    name: "CR-V Black",
    image: "/CR - V-Black.png",
    gallery: [
      "/CR-V Black1.jpg",
      "/CR-V Black2.jpg",
      "/CR-V Black3.jpg",
      "/CR-V Black4.jpg",
    ],
    seat_capacity: 3,
    fuel_capacity: 29,
    transmission: "Automatic",
    type: "SUV",
    company_name: "Honda",
    rental_price_per_day: 247.24,
    previous_rental_price: 260.0,
    color: "#31e463",
    availability: true,
    description:
      "The CR-V Black edition combines elegant styling with cutting-edge technology, offering a luxurious and powerful ride.",
  },
  {
    id: 9,
    name: "MG ZX Exclusive Skyblue",
    image: "/MG-ZX-Excite-Sky.png",
    gallery: [
      "/MG ZX Exclusive Skyblue1.jpg",
      "/MG ZX Exclusive Skyblue2.jpg",
      "/MG ZX Exclusive Skyblue3.jpg",
      "/MG ZX Exclusive Skyblue4.jpg",
    ],
    seat_capacity: 4,
    fuel_capacity: 88,
    transmission: "Automatic",
    type: "Coupe",
    company_name: "Enterprise",
    rental_price_per_day: 284.97,
    previous_rental_price: 300.0,
    color: "#91b71c",
    availability: true,
    description:
      "The MG ZX Exclusive Skyblue is a stunning coupe that delivers a sleek design, advanced features, and dynamic driving performance.",
  },
  {
    id: 10,
    name: "New MG Zs",
    image: "/NewMG-ZS.png",
    gallery: [
      "/New MG Zs1.jpg",
      "/New MG Zs2.jpg",
      "/New MG Zs3.jpg",
      "/New MG Zs4.jpg",
    ],
    seat_capacity: 6,
    fuel_capacity: 91,
    transmission: "Automatic",
    type: "SUV",
    rental_price_per_day: 467.42,
    previous_rental_price: 480.0,
    color: "#e47031",
    availability: true,
    description:
      "Built for adventure, the New MG Zs features a spacious interior, modern infotainment system, and powerful engine performance.",
  },
  {
    id: 11,
    name: "All New Terios",
    image: "/AllNewTerios.png",
    gallery: [
      "/All New Terios1-1.jpg",
      "/All New Terios1-2.jpg",
      "/All New Terios1-3.jpg",
      "/All New Terios1-4.jpg",
    ],
    seat_capacity: 1,
    fuel_capacity: 66,
    transmission: "Manual",
    type: "SUV",
    rental_price_per_day: 236.04,
    previous_rental_price: 250.0,
    color: "#fbb6aa",
    availability: true,
    description:
      "With rugged capabilities and a bold exterior, the All New Terios is built to handle any terrain while providing a comfortable ride.",
  },
  {
    id: 12,
    name: "MG ZX Excite",
    image: "/MG-ZX-Excite-Sky.png",
    gallery: [
      "/MG ZX Excite1-1.jpg",
      "/MG ZX Excite1-2.jpg",
      "/MG ZX Excite1-3.jpg",
      "/MG ZX Excite1-4.jpg",
    ],
    seat_capacity: 2,
    fuel_capacity: 83,
    transmission: "Automatic",
    type: "Sedan",
    rental_price_per_day: 398.39,
    previous_rental_price: 420.0,
    color: "#96fc71",
    availability: true,
    description:
      "A sleek and modern sedan, the MG ZX Excite delivers outstanding performance with stylish aesthetics and premium comfort.",
  },
];
